parameters:
#    affect_frontend.example.class: Affect\FrontendBundle\Example

services:
#    affect_frontend.example:
#        class: %affect_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
